### ISSUE TITLE
Problema do site ficando todo verde

### ISSUE THREAD

**Issue by allanaavila** [allanaavila/templateModulo2#1]
### Problema de Cores

Durante o uso do site, eu vi que quando eu clico no botão de finalizar compra, ele fica todo verde e não aparece mais nada.

Passos para chegar ao erro que eu vi:

- [x] Selecione um produto
- [x] Adicione a quantidade ao carrinho
- [x] Cloque em finalizar compra 
- [x] Veja o erro

**Arrastei a Imagem** 

<img width="1575" alt="Screenshot 2024-05-23 at 7 55 14 PM" src="https://github.com/allanaavila/templateModulo2/assets/61765668/e42745d8-2699-4d3e-8f2a-680bf5e42d8f">

@allanaavila veja esse problema 

#10
#9

**Comment by allanaavila** [comment]
Beleza, encontrei o problema e vou resolver
